// skeletons/frontend/shadcn-skeleton/src/app/page.tsx
import Welcome from "@/components/Welcome";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export default function Home() {
  return (
    <div className="mx-auto flex min-h-screen max-w-3xl flex-col px-4 py-8">
      <header className="mb-8 text-center">
        <h1 className="mb-2 text-4xl font-bold tracking-tight">
          shadcn Skeleton Application
        </h1>
        <p className="text-muted-foreground">
          Built with Next.js + shadcn/ui + TypeScript
        </p>
      </header>

      <main className="flex flex-1 flex-col gap-6">
        <Welcome message="Welcome to your new shadcn/ui application!" />

        <Card>
          <CardHeader>
            <CardTitle>Ready to Build</CardTitle>
            <CardDescription>
              This skeleton application is ready for you to add pages,
              components, and API routes. Use AI-assisted development tools to
              rapidly build your application.
            </CardDescription>
          </CardHeader>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Getting Started</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="list-inside list-disc space-y-2 text-sm text-muted-foreground">
              <li>
                Edit <code className="text-foreground">src/app/page.tsx</code>{" "}
                to modify this page
              </li>
              <li>
                Add shadcn/ui components with{" "}
                <code className="text-foreground">npx shadcn@latest add</code>
              </li>
              <li>
                Create new pages in{" "}
                <code className="text-foreground">src/app/</code> using the App
                Router
              </li>
              <li>
                Add custom components in{" "}
                <code className="text-foreground">src/components/</code>
              </li>
              <li>Fast Refresh is enabled for instant updates</li>
            </ul>
          </CardContent>
        </Card>
      </main>

      <footer className="mt-8 border-t pt-6 text-center text-sm text-muted-foreground">
        <p>
          Edit pages and components to see changes instantly with Fast Refresh
        </p>
      </footer>
    </div>
  );
}

// skeletons/frontend/vue-skeleton/src/components/App.vue
<script setup lang="ts">
import Welcome from './Welcome.vue'
</script>

<template>
  <div class="app-container">
    <header class="app-header">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
      <h1>Vue Skeleton Application</h1>
      <p class="subtitle">Built with Vite + Vue + TypeScript</p>
    </header>

    <main class="app-main">
      <Welcome message="Welcome to your new Vue application!" />

      <div class="info-card">
        <h2>Ready to Build</h2>
        <p>
          This skeleton application is ready for you to add components,
          routes, and functionality. Use AI-assisted development tools
          to rapidly build your application.
        </p>
      </div>

      <div class="getting-started">
        <h3>Getting Started</h3>
        <ul>
          <li>Edit <code>src/components/App.vue</code> to modify this page</li>
          <li>Create new components in <code>src/components/</code></li>
          <li>Add styles in <code>src/styles/</code></li>
          <li>Hot module replacement (HMR) is enabled for instant updates</li>
        </ul>
      </div>
    </main>

    <footer class="app-footer">
      <p>Edit components to see changes instantly with HMR</p>
    </footer>
  </div>
</template>

<style>
@import '../styles/App.css';
</style>
